faceted_navigation:
    image: plone/plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.facetednavigation
    environment:
    - BUILDOUT_EGGS=eea.facetednavigation plone.app.testing
    - BUILDOUT_DEVELOP=src/eea.facetednavigation
